### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by yhnavein**
I've been using angular-tour in a big Angular application and I had to make necessary adjustments, extensions and improvements to the original code to make integration successful. There are no breaking changes, and after my changes apps using original angular-tour should work as before. With those changes angular-tourtip works like a charm in a ~40 controller app. Even having simultaneous tours is possible without any hustle. 

Changes:

* added virtual steps, which allow to specify target element (this allow to have all steps in one place, not messing with having steps spread all over the different views). Moreover, I saw, that sometimes adding **tourtip** attributes to buttons and links can have influence on their behaviour. This is an easy way to fix that kind of problems

* added additional callback on the **tour** level: `tourComplete` - which run only when user fully completed tour

* added additional callbacks on the **tourtip** level: `on-show`, `on-proceed`

* `tourtips` are now appended to the `body`, not to the target's element container. It's important, because this way `tourtip` is more consistent and it's styling doesn't depend on the element it was attached to.

* added optional `backdrop` option

* new available positions: `center` and `center-top` - when using them tourtip will be placed visually in the center of target element. It's good for a welcome `tourtip` on the page.

* added tests around new features and extended README with examples and explanations

Cheers,

### CODE REVIEW

**Comment by bubbleheadinc** [comment]
Good stuff. Any update on merging? Thanks.

**Comment by Carzeh** [comment]
Please merge this!

**Comment by kavarell** [comment]
Any word on when this will be merged?

**Comment by booleanbetrayal** [comment]
@DaftMonk - did this PR get lost in the shuffle?

**Comment by booleanbetrayal** [comment]
@DaftMonk - added support for being able to parent tourtips against a something other than body. would love to see this PR merged!

**Comment by barillax** [comment]
Looks great! +1

**Comment by mathemagica** [comment]
+1

**Comment by mattblang** [comment]
+1

**Comment by booleanbetrayal** [comment]
Merging this!

**Comment by PR-O** [comment]
Nice!

**Comment by yhnavein** [comment]
Yay! :)

**Pull request merged**
