### PR TITLE
Additional vertical/horizontal offset attributes

### PR DESCRIPTION
**Pull request by jwawi**
Adds attributes to be used in template to aid in tourtip placement: tourtip-vertical-offset and tourtip-horizontal-offset. There are many cases (especially those involving transclusion) in which the tourtip placement is somewhat inaccurate.

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
@jwawi - would you mind taking another look at this PR and rebase against master, resolving conflicts?

**Comment by booleanbetrayal** [comment]
@jwawi - it might also be nice if we could keep `offset` as a deprecated configuration property and translate it to the horizontal offset unless its specified as well. I also noticed that the vertical offset is not being applied, so that will need to be fixed.

**Comment by jwawi** [comment]
I was deferring to the existing offset property for elements where that was working and only applying my new props where there wasn't a way to change the horizontal or vertical positioning, but it makes more sense to make the new props available to all cases.

I'll update it to retain the original offset, rename my prop to offsetVertical, and apply that to all cases. rebasing patch conflicts from 35 commits and having tons of fun ;)

**Comment by booleanbetrayal** [comment]
I know ... apologies for that, but there was a lot of work that went into that Improvements PR (#26) that people were clamoring for.  Maybe easier to start fresh? Just let me know!

**Comment by jwawi** [comment]
No worries, I ended up just starting fresh and creating a new PR from branch patch-2. Take a look and let me know if that's what you were looking for.

**Comment by booleanbetrayal** [comment]
Closing in favor of #39

**Pull request closed without merging**
