### PR TITLE
Remove jQuery Dependency - TESTS PENDING

### PR DESCRIPTION
**Pull request by david-meza**
Self explanatory. This library now works without the need of jQuery. As of now all tests are failing because they are still depending on jQuery, but I was hoping that PR could come from another kind soul :). I guess you could make the tests dependent on jQuery (tests 1-29 were all passing, 30 failing then) but I did not want to make that decision. Let me know which things I should change or change back before we can merge to master!

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
hey @david-meza - would love to see this get in, but can't merge it without fixed tests. unfortunately, i don't have any time to dedicate to this project short of reviewing PRs. let me know if you're able to get those tests passing!

**Comment by david-meza** [comment]
I understand. I'll try to re-write those when I get a chance although it may take some time.

**Comment by david-meza** [comment]
Hi! Just wanted to give an update. I have fixed all tests that use jQuery and 29/30 tests are passing. I spent like 2+ hours trying to get the last test to pass but couldn't it figure to save my life. The `scrollTo` service works as intended in development mode, but when in the test mode the function inside `$interval` does not even get called. I tried logging things, and that's where it breaks. If someone could take a look at it, that'd be greatly appreciated. Thanks!

**Comment by booleanbetrayal** [comment]
did you mean to close this @david-meza ? let me know if you plan on re-opening another PR or something.

**Comment by david-meza** [comment]
I opened another PR that uses a feature branch so I can still work in the master branch if I need to @booleanbetrayal

**Pull request closed without merging**
